image: Ubuntu1804

environment:
  matrix:
    - ARCH: aarch64
    - ARCH: x86_64
    - ARCH: armv7
    - ARCH: i686
  
install:
  - sh: |-
      curl -o llvm-mingw.tar.xz    -L https://github.com/mstorsjo/llvm-mingw/releases/download/20191230/llvm-mingw-20191230-ubuntu-16.04.tar.xz
      tar xJf llvm-mingw.tar.xz    || exit 1
      curl -o sdl.tar.gz           -L https://www.libsdl.org/release/SDL2-2.0.10.tar.gz
      tar xzf sdl.tar.gz           || exit 1
      curl -o zlib.tar.xz          -L https://www.zlib.net/zlib-1.2.11.tar.xz
      tar xJf zlib.tar.xz          || exit 1
      curl -o libpng.tar.xz        -L https://download.sourceforge.net/libpng/libpng-1.6.37.tar.xz
      tar xJf libpng.tar.xz        || exit 1
      curl -o openal-soft.tar.bz2  -L https://kcat.strangesoft.net/openal-releases/openal-soft-1.19.1.tar.bz2
      tar xjf openal-soft.tar.bz2  || exit 1
      curl -o freetype.tar.xz      -L https://download.savannah.gnu.org/releases/freetype/freetype-2.10.1.tar.xz
      tar xJf freetype.tar.xz      || exit 1
      curl -o ghostscript.tar.gz   -L https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs950/ghostscript-9.50.tar.gz
      tar xzf ghostscript.tar.gz   || exit 1
      curl -o wpdpack.zip          -L https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip
      7z  x   wpdpack.zip          || exit 1
      git clone https://github.com/driver1998/86box -b rawinput --depth 1
      chmod +x build.sh
      
build_script:
  sh: ./build.sh

after_build:
  sh: |-
    pushd 86box
    COMMIT=$(git describe --always)
    popd
    mv 86Box.zip 86Box-$ARCH-$COMMIT.zip

artifacts:
  - path: '86Box*.zip'
    name: 86Box

deploy:
  - release: $(APPVEYOR_BUILD_NUMBER)
    description: 86Box $(APPVEYOR_BUILD_NUMBER)
    provider: GitHub
    artifact: /86Box.*\.zip/
    auth_token:
      secure: H8HAtJ5SrLHk1gW1eYZFcjtekn1rIW7a8GJsNC6Nftcql8wE0seZRtYqMnFoQLnr
    draft: true
